module(
    name = "great-falls-tool-bus-infra",
    version = "0.1.0",
    compatibility_level = 1,
)

bazel_dep(name = "attic-iac", version = "0.1.0")
bazel_dep(name = "rules_shell", version = "0.6.1")

git_override(
    module_name = "attic-iac",
    remote = "https://github.com/tinyland-inc/GloriousFlywheel.git",
    commit = "f26b541d1d7600d56b2e78c87038415fa06b3622",
)
