apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: latoolb-us-production
resources:
  - maildomain-latoolb-us.yaml
  - mailaccount-keyholders.yaml
  - mailalias-rfc2142.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: great-falls-tool-bus-infra
      app.kubernetes.io/part-of: great-falls-tool-bus
      app.tinyland.dev/tenant: great-falls-tool-bus
